### ISSUE TITLE
grunt and meteor not running at the same time.  Crash.

### ISSUE THREAD

**Issue by timhaines** [SamHatoum/meteor-rtd-example-project#10]
Following the instructions in the readme..

When I run meteor first, and then grunt, meteor crashes with 'Terminated: 15'

When I run grunt first, meteor won't start, saying "Can't listen on port 3000. Perhaps another Meteor is running?"

When I run grunt first, and try running meteor on a different port (say 3005 or 8080), I get a mongo error repeated 3 times before meteor gives up: Unexpected mongo exit code 100. Restarting. 

Using Meteor Release 0.6.3.1

**Comment by SamHatoum** [comment]
Hey Tim. RTD starts meteor for you on port 3000. When it first starts, it kills any existing meteor/mongo instances

**Comment by timhaines** [comment]
Hey, so it does!  :-)   To help future newbs, maybe the output of the grunt file (and readme) could let you know it does that?

**Comment by timhaines** [comment]
Also - Thank you!

**Comment by xolvio** [comment]
it used to, then I thought turning off all the noise was a good thing. Perhaps some info is not noise. I'll add in the next update.

**Comment by xolvio** [comment]
and your'e welcome!
