### ISSUE TITLE
Error: Command Failed

### ISSUE THREAD

**Issue by leedavidr** [SamHatoum/meteor-rtd-example-project#19]
After manually downloading test/rtd (git submodule update didn't work for me), when I run grunt in test/rtd, I'm getting an error while Waiting...>> Error: Command failed:  Any idea what's wrong?  I'm on Ubuntu 64bit

$ grunt

Downloading http://chromedriver.googlecode.com/files/chromedriver_linux64_2.0.zip
.....................................................

Downloading http://selenium.googlecode.com/files/selenium-server-standalone-2.32.0.jar
................................................................................
................................................................................
.....................................................................
File "test/rtd/lib/bin/" created.
Launching Selenium-server on port 4444
Launching Karma listener on port 9876
Launching Karma runner on port 9100
Launching Meteor on port 3000
Launching Mirror on port 8000
Waiting...>> Error: Command failed:
Fatal error: Command failed: 

$ grunt
Launching Selenium-server on port 4444
Launching Karma listener on port 9876
Launching Karma runner on port 9100
Launching Meteor on port 3000
Launching Mirror on port 8000
Waiting...>> Error: Command failed:
Fatal error: Command failed: 

$ grunt
Launching Selenium-server on port 4444
Launching Karma listener on port 9876
Launching Karma runner on port 9100
Launching Meteor on port 3000
Launching Mirror on port 8000
Waiting...>> Error: Command failed:

**Comment by leedavidr** [comment]
I ran ./rtd --debug
and found I had some permission issues.

**Comment by xolvio** [comment]
Thanks for letting us know
