### ISSUE TITLE
Code coverage report Branches for server/leaderboard.js is 50%

### ISSUE THREAD

**Issue by lc3t35** [SamHatoum/meteor-rtd-example-project#20]
As displayed by report :

<pre>
Meteor.startup(function () {
        E if (Players.find().count() === 0) { 
</pre>

This is done once at startup, so the branch count() !== 0 is not covered by tests.

**Comment by xolvio** [comment]
That will be because unit tests coverage combining is disabled until I figure out the issue with istanbul. I'll be back on that soon as I'm loaded with my startup work. I'll keep this open until I sort it

**Comment by xolvio** [comment]
I've fixed this now, please see here:

https://github.com/xolvio/rtd/issues/28
