### ISSUE TITLE
*** PLEASE LEAVE RTD RELATED ISSUES IN THE RTD PROJECT ***

### ISSUE THREAD

**Issue by xolvio** [SamHatoum/meteor-rtd-example-project#21]
If your issue is related more to RTD than the specific leaderboard example (which uses RTD), please use these links:

[Create a New RTD Issue](https://github.com/xolvio/rtd/issues/new)
[Browse Open RTD Issues](https://github.com/xolvio/rtd/issues?state=open)
[Browse Closed RTD Issues](https://github.com/xolvio/rtd/issues?page=1&state=closed)

Thanks

**Comment by timhaines** [comment]
Maybe renaming this repo to have 'example' in the name would help with that?

**Comment by xolvio** [comment]
I'd like to, but all SEO / links would be lost :S

**Comment by timhaines** [comment]
Github does redirects.  I'm not entirely sure of all the details, but here's their blog post: https://github.com/blog/1508-repository-redirects-are-here

**Comment by xolvio** [comment]
Oooh! That's new(ish). It wasn't supported when I tried to do it before. Thanks :+1: , I'll get on that

**Comment by eprochasson** [comment]
+1, this is a bit confusing. Maybe you should update the blog post as well, some (http://xolv.io/blog/2013/04/unit-testing-with-meteor) are super popular but gives a slightly outdated/confusing story. The whole thing is absolutely brilliant.

**Comment by xolvio** [comment]
Good point, I shall update those things too

**Comment by xolvio** [comment]
done
