### ISSUE TITLE
Jasmine timeout setting

### ISSUE THREAD

**Issue by bowlesdr** [SamHatoum/meteor-rtd-example-project#23]
I was frequently getting the following error once I started modifying this project to test my application:
<code>     timeout: timed out after 5000 msec waiting for spec to complete</code>

There is a setting in test/acceptance/leaderboard.spec.js:
<code>     jasmine.DEFAULT_TIMEOUT_INTERVAL = 20000;</code>

I have found that changing it to the following eliminates my timeout errors:
<code>     jasmine.getEnv().defaultTimeoutInterval = 20000;</code>

**Comment by xolvio** [comment]
Thank you, I'll update and report back here

**Comment by xolvio** [comment]
This has been committed now. Thank you
