### ISSUE TITLE
Exits with Bus error: 10

### ISSUE THREAD

**Issue by dgtlife** [SamHatoum/meteor-rtd-example-project#26]
I have not yet been able to get this demo project to run yet. When I run:
`$ ./rtd --debug`

Selenium, Karma, and Meteor all start up fine ... then I see this:

<pre>
Running "watch" task
[D] Task source: /Users/Derek/DGTLife/WebLab/meteor/meteor-rtd-example-project/test/rtd/node_modules/grunt-contrib-watch/tasks/watch.js
Waiting..../rtd: line 11: 22364 Bus error: 10           grunt --debug
</pre>

and the process exits; then I'm back at the prompt.

I searched for the "Bus error: 10" in this issue queue, but no one seems to have experienced this. I'm running on a MBP with OS X Mavericks with:

node v0.10.20
meteor 0.6.6.2 which I switch down to 0.6.5.1 for rtd
phantomjs 1.9.2-2
karma 0.10.4
grunt-cli v0.1.9
grunt v0.4.1
jasmine-node 1.11.0
istanbul 0.1.44

Any thoughts on which component is complaining about the bus error?

**Comment by xolvio** [comment]
First time I've seen BUS error! I just got a MBP running OSX M as well so I'll give it a spin and report back...

**Comment by xolvio** [comment]
Works here. Seems to be a problem with the way node is installed. Check here:

https://github.com/gruntjs/grunt-contrib-watch/issues/204

Hope that helps

**Comment by xolvio** [comment]
Let me know how you go

**Comment by dgtlife** [comment]
Yup. I moved up to node 0.10.21 and all components are happy now. Thanks for the quick response.  
PS: I stayed on 0.10.20 because Meteor 0.6.6.2 is still tracking that version. Hopefully, this node upgrade doesn't precipitate other issues :-)
