### ISSUE TITLE
"Can't find variable: share" when trying to setup against project using coffeescript

### ISSUE THREAD

**Issue by jonathanmoffatt** [SamHatoum/meteor-rtd-example-project#28]
I'm hoping this is a just a newbie problem that someone's run into before. I'm trying to get RTD setup against my meteor project. However we are using coffeescript and consequentially are making use of the "share" object that meteor exposes to get around coffeescript's file-level scoping (http://docs.meteor.com/#coffeescript).

When RTD gets to the "running unit tests" stage we just get "ReferenceError: Can't find variable: share" against all our source files that use the "share" object.

Can anyone suggest any workarounds or fixes for this?

**Comment by SamHatoum** [comment]
Ah, it looks like we need to add the share object to the [Meteor stub](https://github.com/xolvio/rtd/blob/master/lib/meteor-stubs.js). Try to do that and let me know if it works, or better yet create a pull request :)

**Comment by SamHatoum** [comment]
Add the share object to the [vars line](https://github.com/xolvio/rtd/blob/master/lib/meteor-stubs.js#L2):

```
var Npm, Deps, ..., share;
```

And then initialize it [after line 226](https://github.com/xolvio/rtd/blob/master/lib/meteor-stubs.js#L226) with:

```
share = {};
```

Let me know how it goes.

**Comment by jonathanmoffatt** [comment]
Thanks Sam, worked like a charm. I've created a pull request as suggested. Thanks for all the work on RTD btw - it's saved me masses of time. Great to have a "works-out-of-the-box" CI and TDD stack!

**Comment by xolvio** [comment]
Great to hear and glad you're finding RTD useful
