### ISSUE TITLE
problem starting up

### ISSUE THREAD

**Issue by ryw** [SamHatoum/meteor-rtd-example-project#29]
Trying to test out RTD, followed instructions from README, but when I run `grunt`, `test/acceptance/leaderboard.spec.js` errors on line 9.

**Fatal error: Error: Cannot find module '../rtd/node_modules/selenium-webdriver'**

https://github.com/xolvio/meteor-rtd-example-project/blob/master/test/acceptance/leaderboard.spec.js#L9

Here are the contents of my `node_modules` directory within rtd directory... no selenium-webdriver:

freeport
growl
grunt
grunt-bg-shell
grunt-contrib-coffee
grunt-contrib-jshint
grunt-contrib-watch
grunt-cucumber
grunt-exec
grunt-zip
hash_file
karma-chrome-launcher
karma-coffee-preprocessor
karma-coverage
karma-firefox-launcher
karma-html2js-preprocessor
karma-jasmine
karma-junit-reporter
karma-phantomjs-launcher
karma-requirejs
karma-script-launcher
libnotify
request
requirejs

Thoughts?

**Comment by xolvio** [comment]
Hi. It looks like webdriver didn't install. It's in the packages.json so when you do npm install is should be downloaded. Try to do `npm install` inside the RTD directory and try again

**Comment by ryw** [comment]
thanks — this solved my issue.
