### ISSUE TITLE
Error when following Readme.md instructions

### ISSUE THREAD

**Issue by alanning** [SamHatoum/meteor-rtd-example-project#3]
Executing 'npm install' followed by 'grunt' produces the following error on OSX.  This may be caused by an over-zealous .gitignore (excluding .meteor directory); or just need to update instructions with how to properly set up the Meteor project.

```
Running "bgShell:startPhantom" (bgShell) task

Running "bgShell:startAcceptanceApp" (bgShell) task

Running "bgShell:startKarma" (bgShell) task

Running "bgShell:startApp" (bgShell) task

Running "watch" task
Waiting...run: You're not in a Meteor project directory.

To create a new Meteor project:
   meteor create <project name>
For example:
   meteor create myapp

For more help, see 'meteor --help'.
>> Error: Command failed:
Fatal error: Command failed:
```

**Comment by xolvio** [comment]
Fixed. It's due to the acceptance-app not being synchronized with the main app prior to the grunt script starting. I've also renamed the acceptance-app to mirror_app to make it clearer what this is.
