### ISSUE TITLE
Coverage is not generated 

### ISSUE THREAD

**Issue by Maxim-Filimonov** [SamHatoum/meteor-rtd-example-project#41]
So I tried to run RTD on this project according to README and seems to not working.
First, there is a problem with jasmine-node -> https://github.com/mhevery/jasmine-node/issues/330
Which I've managed to fix by putting `jasmine-reports: "^1.0.0` in package.json.
But even after that I can't make it work. 
All test pass but looks like coverage is not generated 

```
./node_modules/.bin/rtd runOnce --debug
....
Running "postLatestUnitCoverage" task
[D] Task source: /Users/maxim/repos/meteor_learning/meteor-rtd-example-project/node_modules/rtd/Gruntfile.js
No coverage reports available from unit tests
```

See [full log](https://gist.github.com/Maxim-Filimonov/cc25fc136aa1343c7bbb)
Any ideas?

**Comment by alanning** [comment]
Not sure why coverage reports are not working but I wanted to let you know about the [velocity](https://github.com/xolvio/velocity) project which is a successor to RTD.  We don't have coverage reports yet but plan to include those.

@samhatoum can way in with the official word but my impression is that RTD is being sun-setted in favor of velocity.

**Comment by SamHatoum** [comment]
Yes, all hands on deck are on velocity at the moment, I've yet to make that official as I want to fully support everything that RTD does currently to make the transition for existing RTD smooth.

As for the question itself, do you have coverage report files being generated under the `PROJECT_BASE_PATH + '/build/reports/coverage'` directory?

**Comment by Maxim-Filimonov** [comment]
Ah right I'll start looking at velocity then.
@samhatoum nope they are not generated.

```
tree build
build
├── mirror_app
│   ├── client
│   │   ├── leaderboard.html
│   │   └── leaderboard.js
│   ├── css
│   │   └── leaderboard.css
│   ├── models
│   │   └── Players.js
│   ├── packages
│   │   ├── istanbul-middleware-port -> /Users/maxim/repos/meteor_learning/meteor-rtd-example-project/node_modules/rtd/lib/istanbul-middleware-port
│   │   └── meteor-fixture -> /Users/maxim/repos/meteor_learning/meteor-rtd-example-project/node_modules/rtd/lib/meteor-fixture
│   ├── public
│   │   ├── favicon.ico
│   │   └── robots.txt
│   └── server
│       ├── fixture.js
│       └── leaderboard.js
└── reports
    ├── TEST-Leaderboardfunctionality.xml
    └── TEST-UnitTests.xml

10 directories, 10 files
```

**Comment by SamHatoum** [comment]
How odd. Did you add a custom karma.conf.js? It's actually karma that [does the unit-test instrumentation](https://github.com/xolvio/rtd/blob/master/karma.conf.js#L81)

**Comment by Maxim-Filimonov** [comment]
Nope haven't touched anything. 
Just cloned the repo and added `jasmine_reporters: "^1.0.0"` to package.json
BTW just found out that jasmine-node problem affects velocity examples too :(

**Comment by alanning** [comment]
@Maxim-Filimonov That jasmine-node / reporters problem should be fixed in the velocity examples since we updated jasmine-unit.  If its still causing errors, please report that on the jasmine-unit [issues tracker](https://github.com/xolvio/jasmine-unit/issues?state=open).

In particular we tracked those issues in these closed tickers here: 

https://github.com/xolvio/jasmine-unit/issues/19
https://github.com/xolvio/jasmine-unit/issues/21

If you are still seeing one of those issues, please re-open the appropriate ticket.

**Comment by SamHatoum** [comment]
I'll try to checkout the project later and see if I can repeat it. Thanks for reporting :+1:

**Comment by Maxim-Filimonov** [comment]
@samhatoum @alanning thanks for your helping with figuring this out.
After applying https://github.com/xolvio/rtd/pull/169 manually I've managed to make example working again with fresh git clone :+1: 
Closing this one, than :)
