### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by sbking** [SamHatoum/meteor-rtd-example-project#5]
I'm trying to figure out how to get this project to work but it's just not happening for me. I can't figure out how to test any of my coffeescript files or how to make tests written in coffeescript work. I don't see any tests being run in the console. My test reports don't show any of my code outside of `client/`, `models/`, and `server/`. It seems like everything is set up right but I just can't figure out how to use it.

**Comment by xolvio** [comment]
Hi there.

Sadly I'm not adept with coffeescript yet, but I'll try to help where I can.

Have you see this article? http://blog.xolv.io/2013/04/unit-testing-with-meteor.html - it explains the approach there.

**Comment by xolvio** [comment]
Let me know if you still need help. I'm closing this issue.
