### ISSUE TITLE
This setting crashes mongodb when MONGO_URL is set

### ISSUE THREAD

**Issue by shoehn** [SamHatoum/meteor-rtd-example-project#6]
Hello,

when I try to start your setting as described in the README.md everything works perfect as long as I use the embedded minimongo.

Trying to use a real mongodb the script kills my mongodb. 

I am on OSX 10.8 using Node v0.10.4 and Meteor 0.6.2.1

Did you encounter this issue? Starting the meteor app without the testing infrastructure works as expected.

Best regards

Sebastian

**Comment by xolvio** [comment]
Hey Sebastian. I haven't gotten around to setting up an external mongo yet. I'll do that and see what the problem is. When you say "kills the mongodb", what do you mean?

**Comment by shoehn** [comment]
It stops the mongo instance, so that it is no longer running. I did not figure out yet whether mongo crashes or the scripts stop it.

That's what I find in the logs:

> Thu Apr 25 09:58:42 got signal 15 (Terminated: 15), will terminate after current cmd ends

So terminating mongod is the right answer to this signal. But as I said I will try to figure out which application sends the signal.

**Comment by xolvio** [comment]
Aha. It's line 29 in gruntfile.js You can see when RTD starts, it kills mongod just in case. Obviously this is not a good idea when you have a separate running mongod server :-) You should remove that line.

You may also want to use a different database for the mirrorApp (line 44)

**Comment by shoehn** [comment]
Thank you very much. That is really fast support. This solved the issue. Should have found that myself, but I did not think about the possibility that the gruntfile shuts down mongod ;-)
