### ISSUE TITLE
Missing install instructions

### ISSUE THREAD

**Issue by alanning** [SamHatoum/meteor-rtd-example-project#7]
A couple more pieces that are required before end-to-end testing works:

1.

> npm install -g jasmine-node

2.
You should download the latest chromeDriver and move it into a location in your PATH
http://code.google.com/p/chromedriver/downloads/list
To see the folders in your PATH, do the following...
Linux/Mac:

> echo $PATH
> Win:
> echo %PATH%

**Comment by xolvio** [comment]
Thanks Adrian, funnily enough I've just came to the same conclusion. I had chromedriver in the same directory as selenium-server and was not aware that's why it worked.

In any case, if you look here: https://github.com/xolvio/rtd - this is git submodule you can add. This version downloads selenium if it doesn't exist. I'll make it also do chrome.

Thanks for the correction, I'll iterate once this project uses the submodule also.

**Comment by alanning** [comment]
Yeah, its hard to distinguish that kind of stuff when it's our main dev
box. I've recently been setting up a VirtualBox to use to test deployment
scripts (using pallet) and am running into similar issues.

One thing I'm surprised about is that the jasmine-node piece needs to be
installed globally rather than locally. Any ideas as to why that is?

Sent from my phone

On Apr 26, 2013, at 4:03 PM, Xolvio notifications@github.com wrote:

Thanks Adrian, funnily enough I've just came to the same conclusion. I had
chromedriver in the same directory as selenium-server and was not aware
that's why it worked.

In any case, if you look here: https://github.com/xolvio/rtd - this is git
submodule you can add. This version downloads selenium if it doesn't exist.
I'll make it also do chrome.

Thanks for the correction, I'll iterate once this project uses the
submodule also.

—
Reply to this email directly or view it on
GitHubhttps://github.com/xolvio/real-time-development-with-meteor/issues/7#issuecomment-17097031
.

**Comment by xolvio** [comment]
Because it's a command line tool, I believe. It would also be possible to require jasmine and then have it run as a standard node app

**Comment by alanning** [comment]
Ahh, that makes sense.  Somehow I thought Grunt would set up something
fancy re: PATH management but it wouldn't actually know its an executable
so don't think that would work.
